In [1]:
# %pip install nba_api

In [2]:
import pandas as pd

In [3]:
from nba_api.stats.static import teams

In [4]:
type(teams)

module

Trying to find all methods associated to the module

In [5]:
dir(teams)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_find_team_by_abbreviation',
 '_find_team_name_by_id',
 '_find_teams',
 '_find_teams_by_championship_year',
 '_find_teams_by_year_founded',
 '_get_team_dict',
 '_get_teams',
 'find_team_by_abbreviation',
 'find_team_name_by_id',
 'find_teams_by_championship_year',
 'find_teams_by_city',
 'find_teams_by_full_name',
 'find_teams_by_nickname',
 'find_teams_by_state',
 'find_teams_by_year_founded',
 'find_wnba_team_by_abbreviation',
 'find_wnba_team_name_by_id',
 'find_wnba_teams_by_championship_year',
 'find_wnba_teams_by_city',
 'find_wnba_teams_by_full_name',
 'find_wnba_teams_by_nickname',
 'find_wnba_teams_by_state',
 'find_wnba_teams_by_year_founded',
 'get_teams',
 'get_wnba_teams',
 're',
 'team_index_abbreviation',
 'team_index_championship_year',
 'team_index_city',
 'team_index_full_name',
 'team_index_id',
 'team_index_nickname',
 'team_index_state',
 'team_index_year_founded',
 'teams',
 'wnba_teams']

In [6]:
nba_teams = teams.get_teams()

Number of teams in the NBA

In [7]:
nba_teams[0]
len(nba_teams)

30

Teams and their team id's, going to need this later to query all players from each team

In [8]:
for team in nba_teams:
    print(team['id'], team['abbreviation'])

1610612737 ATL
1610612738 BOS
1610612739 CLE
1610612740 NOP
1610612741 CHI
1610612742 DAL
1610612743 DEN
1610612744 GSW
1610612745 HOU
1610612746 LAC
1610612747 LAL
1610612748 MIA
1610612749 MIL
1610612750 MIN
1610612751 BKN
1610612752 NYK
1610612753 ORL
1610612754 IND
1610612755 PHI
1610612756 PHX
1610612757 POR
1610612758 SAC
1610612759 SAS
1610612760 OKC
1610612761 TOR
1610612762 UTA
1610612763 MEM
1610612764 WAS
1610612765 DET
1610612766 CHA

Finding players - searching my team id

In [9]:
from nba_api.stats.endpoints import playerindex

In [10]:
players = playerindex.PlayerIndex(team_id_nullable='1610612757')

In [11]:
por_players = players.get_data_frames()[0]

In [12]:
por_players.head()

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,JERSEY_NUMBER,...,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,FROM_YEAR,TO_YEAR,PTS,REB,AST,STATS_TIMEFRAME
0,1630166,Avdija,Deni,deni-avdija,blazers,1610612757,Portland,Trail Blazers,POR,8,...,2020.0,1.0,9.0,1.0,2020,2025,24.2,6.9,6.7,Season
1,1641739,Camara,Toumani,toumani-camara,blazers,1610612757,Portland,Trail Blazers,POR,33,...,2023.0,2.0,52.0,1.0,2023,2025,13.4,5.1,2.5,Season
2,1631321,Cissoko,Sidy,sidy-cissoko,blazers,1610612757,Portland,Trail Blazers,POR,91,...,2023.0,2.0,44.0,1.0,2023,2025,5.1,2.2,1.5,Season
3,1642270,Clingan,Donovan,donovan-clingan,blazers,1610612757,Portland,Trail Blazers,POR,23,...,2024.0,1.0,7.0,1.0,2024,2025,12.1,11.6,2.1,Season
4,203924,Grant,Jerami,jerami-grant,blazers,1610612757,Portland,Trail Blazers,POR,9,...,2014.0,2.0,39.0,1.0,2014,2025,18.6,3.5,2.1,Season

In [13]:
por_players.sort_values('TO_YEAR', ascending=False)

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,JERSEY_NUMBER,...,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,FROM_YEAR,TO_YEAR,PTS,REB,AST,STATS_TIMEFRAME
0,1630166,Avdija,Deni,deni-avdija,blazers,1610612757,Portland,Trail Blazers,POR,8,...,2020.0,1.0,9.0,1.0,2020,2025,24.2,6.9,6.7,Season
1,1641739,Camara,Toumani,toumani-camara,blazers,1610612757,Portland,Trail Blazers,POR,33,...,2023.0,2.0,52.0,1.0,2023,2025,13.4,5.1,2.5,Season
16,1642905,Hansen,Yang,yang-hansen,blazers,1610612757,Portland,Trail Blazers,POR,16,...,2025.0,1.0,16.0,1.0,2025,2025,2.2,1.5,0.5,Season
15,1629057,Williams III,Robert,robert-williams-iii,blazers,1610612757,Portland,Trail Blazers,POR,35,...,2018.0,1.0,27.0,1.0,2018,2025,6.7,7.0,1.0,Season
14,1631104,Wesley,Blake,blake-wesley,blazers,1610612757,Portland,Trail Blazers,POR,1,...,2022.0,1.0,25.0,1.0,2022,2025,4.8,1.3,2.0,Season
13,1629680,Thybulle,Matisse,matisse-thybulle,blazers,1610612757,Portland,Trail Blazers,POR,4,...,2019.0,1.0,20.0,1.0,2019,2025,5.8,2.0,0.9,Season
12,1631101,Sharpe,Shaedon,shaedon-sharpe,blazers,1610612757,Portland,Trail Blazers,POR,17,...,2022.0,1.0,7.0,1.0,2022,2025,20.8,4.3,2.6,Season
11,1631200,Murray,Kris,kris-murray,blazers,1610612757,Portland,Trail Blazers,POR,24,...,2023.0,1.0,23.0,1.0,2023,2025,5.8,3.6,1.4,Season
10,1631126,Love,Caleb,caleb-love,blazers,1610612757,Portland,Trail Blazers,POR,2,...,NaN,NaN,NaN,1.0,2025,2025,10.4,2.3,2.5,Season
9,203081,Lillard,Damian,damian-lillard,blazers,1610612757,Portland,Trail Blazers,POR,0,...,2012.0,1.0,6.0,1.0,2012,2025,NaN,NaN,NaN,Season
8,1630249,Krejčí,Vít,vít-krejčí,blazers,1610612757,Portland,Trail Blazers,POR,27,...,2020.0,2.0,37.0,1.0,2021,2025,8.5,2.3,1.5,Season
7,1643257,Kent,Jayson,jayson-kent,blazers,1610612757,Portland,Trail Blazers,POR,NaN,...,NaN,NaN,NaN,1.0,2025,2025,2.0,1.0,0.0,Season
6,201950,Holiday,Jrue,jrue-holiday,blazers,1610612757,Portland,Trail Blazers,POR,5,...,2009.0,1.0,17.0,1.0,2009,2025,16.3,4.6,6.1,Season
5,1630703,Henderson,Scoot,scoot-henderson,blazers,1610612757,Portland,Trail Blazers,POR,00,...,2023.0,1.0,3.0,1.0,2023,2025,14.2,2.7,3.7,Season
4,203924,Grant,Jerami,jerami-grant,blazers,1610612757,Portland,Trail Blazers,POR,9,...,2014.0,2.0,39.0,1.0,2014,2025,18.6,3.5,2.1,Season
3,1642270,Clingan,Donovan,donovan-clingan,blazers,1610612757,Portland,Trail Blazers,POR,23,...,2024.0,1.0,7.0,1.0,2024,2025,12.1,11.6,2.1,Season
2,1631321,Cissoko,Sidy,sidy-cissoko,blazers,1610612757,Portland,Trail Blazers,POR,91,...,2023.0,2.0,44.0,1.0,2023,2025,5.1,2.2,1.5,Season
17,1642959,Youngblood,Chris,chris-youngblood,blazers,1610612757,Portland,Trail Blazers,POR,3,...,NaN,NaN,NaN,1.0,2025,2025,2.1,0.8,0.4,Season

In [14]:
draft_2020 = playerindex.PlayerIndex(team_id_nullable='1610612757', draft_year_nullable='2020')

In [15]:
draft_2020.get_data_frames()[0]

,PERSON_ID,PLAYER_LAST_NAME,PLAYER_FIRST_NAME,PLAYER_SLUG,TEAM_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,JERSEY_NUMBER,...,DRAFT_YEAR,DRAFT_ROUND,DRAFT_NUMBER,ROSTER_STATUS,FROM_YEAR,TO_YEAR,PTS,REB,AST,STATS_TIMEFRAME
0,1630166,Avdija,Deni,deni-avdija,blazers,1610612757,Portland,Trail Blazers,POR,8,...,2020,1,9,1.0,2020,2025,24.2,6.9,6.7,Season
1,1630249,Krejčí,Vít,vít-krejčí,blazers,1610612757,Portland,Trail Blazers,POR,27,...,2020,2,37,1.0,2021,2025,8.5,2.3,1.5,Season

NOTE: not all columns are made equal, need to check using dtypes and potentially convert

In [17]:
por_players.dtypes

PERSON_ID              int64
PLAYER_LAST_NAME         str
PLAYER_FIRST_NAME        str
PLAYER_SLUG              str
TEAM_SLUG                str
TEAM_ID                int64
TEAM_CITY                str
TEAM_NAME                str
TEAM_ABBREVIATION        str
JERSEY_NUMBER            str
POSITION                 str
HEIGHT                   str
WEIGHT                   str
COLLEGE                  str
COUNTRY                  str
DRAFT_YEAR           float64
DRAFT_ROUND          float64
DRAFT_NUMBER         float64
ROSTER_STATUS        float64
FROM_YEAR                str
TO_YEAR                  str
PTS                  float64
REB                  float64
AST                  float64
STATS_TIMEFRAME          str
dtype: object

Trying to find player stats

In [18]:
from nba_api.stats.endpoints import playerdashboardbylastngames

In [19]:
player_stats = playerdashboardbylastngames.PlayerDashboardByLastNGames(player_id='1629057', last_n_games=20)

In [20]:
player_stats.get_data_frames()[0]

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
0,Overall,2025-26,17,10,7,0.588,321.613333,58,89,0.652,...,1,1,1,1,1,1,1,1,1,1

In [21]:
dir(players)

['DataSet',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'data_sets',
 'endpoint',
 'expected_data',
 'get_available_data',
 'get_data_frames',
 'get_dict',
 'get_json',
 'get_normalized_dict',
 'get_normalized_json',
 'get_request',
 'get_request_url',
 'get_response',
 'headers',
 'load_response',
 'nba_response',
 'parameters',
 'player_index',
 'player_stats',
 'proxy',
 'team_stats',
 'timeout']

Finding players and player ids from players directory

In [22]:
from nba_api.stats.static import players

In [23]:
dir(players)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_find_player_by_id',
 '_find_players',
 '_get_active_players',
 '_get_inactive_players',
 '_get_player_dict',
 '_get_players',
 '_strip_accents',
 'find_player_by_id',
 'find_players_by_first_name',
 'find_players_by_full_name',
 'find_players_by_last_name',
 'find_wnba_player_by_id',
 'find_wnba_players_by_first_name',
 'find_wnba_players_by_full_name',
 'find_wnba_players_by_last_name',
 'get_active_players',
 'get_inactive_players',
 'get_players',
 'get_wnba_active_players',
 'get_wnba_inactive_players',
 'get_wnba_players',
 'player_index_first_name',
 'player_index_full_name',
 'player_index_id',
 'player_index_is_active',
 'player_index_last_name',
 'players',
 're',
 'unicodedata',
 'wnba_players']

In [24]:
players.find_players_by_first_name('lebron')

[{'id': 2544,
  'full_name': 'LeBron James',
  'first_name': 'LeBron',
  'last_name': 'James',
  'is_active': True}]

Trying to query for one player to retrieve stats

In [25]:
from nba_api.stats.endpoints import playerdashboardbyteamperformance

In [26]:
james = playerdashboardbyteamperformance.PlayerDashboardByTeamPerformance(player_id='2544')

In [27]:
frames = james.get_data_frames()

In [28]:
frames[1]

,GROUP_SET,GROUP_VALUE_ORDER,GROUP_VALUE,GROUP_VALUE_2,GP,W,L,W_PCT,MIN,FGM,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
0,Score Differential,0.0,W,All,39,39,0,1.0,1290.613333,314,...,2,2,1,1,1,1,1,1,1,1
1,Score Differential,NaN,W,6-10 Points,13,13,0,1.0,452.403333,110,...,10,10,1,1,3,1,1,2,1,1
2,Score Differential,NaN,W,5 Points and Under,8,8,0,1.0,285.823333,56,...,9,9,5,4,6,4,3,3,4,1
3,Score Differential,NaN,W,11-15 Points,4,4,0,1.0,126.350000,24,...,1,7,7,9,5,9,7,3,9,1
4,Score Differential,NaN,W,16-20 Points,7,7,0,1.0,231.466667,62,...,6,4,2,3,2,2,2,1,2,1
5,Score Differential,NaN,W,Over 20 Points,7,7,0,1.0,194.570000,62,...,5,1,3,2,1,3,3,3,3,1
6,Score Differential,0.0,L,All,21,0,21,0.0,698.441667,159,...,1,1,2,2,2,2,2,2,2,1
7,Score Differential,NaN,L,16-20 Points,3,0,3,0.0,96.400000,19,...,2,1,9,10,8,10,9,3,10,1
8,Score Differential,NaN,L,Over 20 Points,6,0,6,0.0,177.716667,35,...,8,8,3,5,10,6,9,3,5,1
9,Score Differential,NaN,L,6-10 Points,4,0,4,0.0,144.266667,37,...,2,4,6,7,7,5,3,3,6,1
10,Score Differential,NaN,L,11-15 Points,4,0,4,0.0,141.825000,39,...,4,1,7,6,9,7,7,3,7,1
11,Score Differential,NaN,L,5 Points and Under,4,0,4,0.0,138.233333,29,...,6,4,9,8,4,8,3,3,8,1

Lots of this data does not make sense (to me)

In [29]:
frames[0]

,GROUP_SET,GROUP_VALUE,GP,W,L,W_PCT,MIN,FGM,FGA,FG_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
0,Overall,2025-26,60,39,21,0.65,1989.055,473,919,0.515,...,1,1,1,1,1,1,1,1,1,1

In [30]:
from nba_api.stats.endpoints import playercareerstats

In [31]:
player_stats = playercareerstats.PlayerCareerStats(player_id='2544')

In [33]:
stats = player_stats.get_data_frames()[4]

In [34]:
stats

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,2544,2004-05,00,1610616833,EST,20.0,1,1,31,6,...,0.00,1,7,8,6,2,0,3,0,13
1,2544,2005-06,00,1610616833,EST,21.0,1,1,31,12,...,0.20,2,4,6,2,2,0,1,2,29
2,2544,2006-07,00,1610616833,EST,22.0,1,1,32,11,...,1.00,0,6,6,6,1,0,4,0,28
3,2544,2007-08,00,1610616833,EST,23.0,1,1,30,12,...,1.00,1,7,8,9,2,2,4,3,27
4,2544,2008-09,00,1610616833,EST,24.0,1,1,27,8,...,1.00,0,5,5,3,0,0,3,0,20
5,2544,2009-10,00,1610616833,EST,25.0,1,1,32,10,...,1.00,1,4,5,6,4,0,2,1,25
6,2544,2010-11,00,1610616833,EST,26.0,1,1,32,10,...,0.90,2,10,12,10,0,0,4,3,29
7,2544,2011-12,00,1610616833,EST,27.0,1,1,32,15,...,0.00,0,6,6,7,0,0,4,2,36
8,2544,2012-13,00,1610616833,EST,28.0,1,1,30,7,...,0.50,0,3,3,5,1,0,4,0,19
9,2544,2013-14,00,1610616833,EST,29.0,1,1,33,11,...,0.00,1,6,7,7,3,0,1,0,22
10,2544,2014-15,00,1610616833,EST,30.0,1,1,32,11,...,0.80,1,4,5,7,2,0,4,1,30
11,2544,2015-16,00,1610616833,EST,31.0,1,1,20,6,...,0.00,0,4,4,7,0,0,4,0,13
12,2544,2016-17,00,1610616833,EST,32.0,1,1,19,10,...,0.00,0,3,3,1,0,0,4,2,23
13,2544,2017-18,00,1610616833,LBN,33.0,1,1,31,12,...,1.00,0,10,10,8,1,0,5,2,29
14,2544,2018-19,00,1610616834,LBN,34.0,1,1,27,9,...,0.00,2,6,8,4,0,2,1,1,19
15,2544,2019-20,00,1610616834,LBN,35.0,1,1,19,9,...,0.75,2,3,5,6,1,2,6,1,23
16,2544,2020-21,00,1610616834,LBN,36.0,1,1,13,2,...,0.00,0,2,2,4,0,1,1,0,4
17,2544,2021-22,00,1610616834,LBN,37.0,1,1,36,11,...,0.00,1,5,6,8,3,1,3,0,24
18,2544,2022-23,00,1610616834,LBN,38.0,1,1,14,6,...,0.00,0,1,1,4,0,0,0,1,13
19,2544,2023-24,00,1610616834,WST,39.0,1,1,14,4,...,0.00,0,4,4,3,0,0,1,0,8
20,2544,2025-26,00,1610616860,STP,41.0,3,3,21,5,...,1.00,4,3,7,5,1,0,2,3,15

NOTE: this is the API to use, to retrieve game data for each player

In [35]:
from nba_api.stats.endpoints import playergamelog

In [36]:
current_gamelog = playergamelog.PlayerGameLog(player_id='2544')

In [37]:
logs = current_gamelog.get_data_frames()[0]

In [38]:
logs.head()

,SEASON_ID,Player_ID,Game_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,...,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS,VIDEO_AVAILABLE
0,22025,2544,0022501198,"Apr 12, 2026",LAL vs. UTA,W,17,6,15,0.400,...,4,4,6,3,0,4,0,18,14,1
1,22025,2544,0022501185,"Apr 10, 2026",LAL vs. PHX,W,32,10,16,0.625,...,6,6,12,4,0,2,1,28,27,1
2,22025,2544,0022501170,"Apr 09, 2026",LAL @ GSW,W,32,11,17,0.647,...,8,8,11,2,1,4,1,26,19,1
3,22025,2544,0022501140,"Apr 05, 2026",LAL @ DAL,L,39,12,22,0.545,...,9,9,15,1,0,4,1,30,1,1
4,22025,2544,0022501116,"Apr 02, 2026",LAL @ OKC,L,26,3,7,0.429,...,6,6,2,1,1,2,1,13,-37,1

In [39]:
logs.dtypes

SEASON_ID              str
Player_ID            int64
Game_ID                str
GAME_DATE              str
MATCHUP                str
WL                     str
MIN                  int64
FGM                  int64
FGA                  int64
FG_PCT             float64
FG3M                 int64
FG3A                 int64
FG3_PCT            float64
FTM                  int64
FTA                  int64
FT_PCT             float64
OREB                 int64
DREB                 int64
REB                  int64
AST                  int64
STL                  int64
BLK                  int64
TOV                  int64
PF                   int64
PTS                  int64
PLUS_MINUS           int64
VIDEO_AVAILABLE      int64
dtype: object

In [41]:
from nba_api.stats.static import players

In [45]:
cur_players = players.get_active_players()

In [46]:
cur_players

[{'id': 1630173,
  'full_name': 'Precious Achiuwa',
  'first_name': 'Precious',
  'last_name': 'Achiuwa',
  'is_active': True},
 {'id': 203500,
  'full_name': 'Steven Adams',
  'first_name': 'Steven',
  'last_name': 'Adams',
  'is_active': True},
 {'id': 1628389,
  'full_name': 'Bam Adebayo',
  'first_name': 'Bam',
  'last_name': 'Adebayo',
  'is_active': True},
 {'id': 1630534,
  'full_name': 'Ochai Agbaji',
  'first_name': 'Ochai',
  'last_name': 'Agbaji',
  'is_active': True},
 {'id': 1630583,
  'full_name': 'Santi Aldama',
  'first_name': 'Santi',
  'last_name': 'Aldama',
  'is_active': True},
 {'id': 1641725,
  'full_name': 'Trey Alexander',
  'first_name': 'Trey',
  'last_name': 'Alexander',
  'is_active': True},
 {'id': 1629638,
  'full_name': 'Nickeil Alexander-Walker',
  'first_name': 'Nickeil',
  'last_name': 'Alexander-Walker',
  'is_active': True},
 {'id': 1628960,
  'full_name': 'Grayson Allen',
  'first_name': 'Grayson',
  'last_name': 'Allen',
  'is_active': True},
 {'id': 1628386,
  'full_name': 'Jarrett Allen',
  'first_name': 'Jarrett',
  'last_name': 'Allen',
  'is_active': True},
 {'id': 1630631,
  'full_name': 'Jose Alvarado',
  'first_name': 'Jose',
  'last_name': 'Alvarado',
  'is_active': True},
 {'id': 203937,
  'full_name': 'Kyle Anderson',
  'first_name': 'Kyle',
  'last_name': 'Anderson',
  'is_active': True},
 {'id': 1630828,
  'full_name': 'Alex Antetokounmpo',
  'first_name': 'Alex',
  'last_name': 'Antetokounmpo',
  'is_active': True},
 {'id': 203507,
  'full_name': 'Giannis Antetokounmpo',
  'first_name': 'Giannis',
  'last_name': 'Antetokounmpo',
  'is_active': True},
 {'id': 203648,
  'full_name': 'Thanasis Antetokounmpo',
  'first_name': 'Thanasis',
  'last_name': 'Antetokounmpo',
  'is_active': True},
 {'id': 1630175,
  'full_name': 'Cole Anthony',
  'first_name': 'Cole',
  'last_name': 'Anthony',
  'is_active': True},
 {'id': 1628384,
  'full_name': 'OG Anunoby',
  'first_name': 'OG',
  'last_name': 'Anunoby',
  'is_active': True},
 {'id': 1630166,
  'full_name': 'Deni Avdija',
  'first_name': 'Deni',
  'last_name': 'Avdija',
  'is_active': True},
 {'id': 1629028,
  'full_name': 'Deandre Ayton',
  'first_name': 'Deandre',
  'last_name': 'Ayton',
  'is_active': True},
 {'id': 1628963,
  'full_name': 'Marvin Bagley III',
  'first_name': 'Marvin',
  'last_name': 'Bagley III',
  'is_active': True},
 {'id': 1642846,
  'full_name': 'Ace Bailey',
  'first_name': 'Ace',
  'last_name': 'Bailey',
  'is_active': True},
 {'id': 1630163,
  'full_name': 'LaMelo Ball',
  'first_name': 'LaMelo',
  'last_name': 'Ball',
  'is_active': True},
 {'id': 1628366,
  'full_name': 'Lonzo Ball',
  'first_name': 'Lonzo',
  'last_name': 'Ball',
  'is_active': True},
 {'id': 1631094,
  'full_name': 'Paolo Banchero',
  'first_name': 'Paolo',
  'last_name': 'Banchero',
  'is_active': True},
 {'id': 1630217,
  'full_name': 'Desmond Bane',
  'first_name': 'Desmond',
  'last_name': 'Bane',
  'is_active': True},
 {'id': 1631230,
  'full_name': 'Dominick Barlow',
  'first_name': 'Dominick',
  'last_name': 'Barlow',
  'is_active': True},
 {'id': 203084,
  'full_name': 'Harrison Barnes',
  'first_name': 'Harrison',
  'last_name': 'Barnes',
  'is_active': True},
 {'id': 1630567,
  'full_name': 'Scottie Barnes',
  'first_name': 'Scottie',
  'last_name': 'Barnes',
  'is_active': True},
 {'id': 1642964,
  'full_name': 'Brooks Barnhizer',
  'first_name': 'Brooks',
  'last_name': 'Barnhizer',
  'is_active': True},
 {'id': 1629628,
  'full_name': 'RJ Barrett',
  'first_name': 'RJ',
  'last_name': 'Barrett',
  'is_active': True},
 {'id': 1629646,
  'full_name': 'Charles Bassey',
  'first_name': 'Charles',
  'last_name': 'Bassey',
  'is_active': True},
 {'id': 1642926,
  'full_name': 'Tamar Bates',
  'first_name': 'Tamar',
  'last_name': 'Bates',
  'is_active': True},
 {'id': 1642419,
  'full_name': 'Jamison Battle',
  'first_name': 'Jamison',
  'last_name': 'Battle',
  'is_active': True},
 {'id': 201587,
  'full_name': 'Nicolas Batum',
  'first_name': 'Nicolas',
  'last_name': 'Batum',
  'is_active': True},
 {'id': 203078,
  'full_name': 'Bradley Beal',
  'first_name': 'Bradley',
  'last_name': 'Beal',
  'is_active': True},
 {'id': 1642866,
  'full_name': 'Joan Beringer',
  'first_name': 'Joan',
  'last_name': 'Beringer',
  'is_active': True},
 {'id': 1630180,
  'full_name': 'Saddiq Bey',
  'first_name': 'Saddiq',
  'last_name': 'Bey',
  'is_active': True},
 {'id': 1629048,
  'full_name': 'Goga Bitadze',
  'first_name': 'Goga',
  'last_name': 'Bitadze',
  'is_active': True},
 {'id': 202687,
  'full_name': 'Bismack Biyombo',
  'first_name': 'Bismack',
  'last_name': 'Biyombo',
  'is_active': True},
 {'id': 1641710,
  'full_name': 'Anthony Black',
  'first_name': 'Anthony',
  'last_name': 'Black',
  'is_active': True},
 {'id': 203992,
  'full_name': 'Bogdan Bogdanović',
  'first_name': 'Bogdan',
  'last_name': 'Bogdanović',
  'is_active': True},
 {'id': 1641737,
  'full_name': 'Adem Bona',
  'first_name': 'Adem',
  'last_name': 'Bona',
  'is_active': True},
 {'id': 1626164,
  'full_name': 'Devin Booker',
  'first_name': 'Devin',
  'last_name': 'Booker',
  'is_active': True},
 {'id': 1628449,
  'full_name': 'Chris Boucher',
  'first_name': 'Chris',
  'last_name': 'Boucher',
  'is_active': True},
 {'id': 1628396,
  'full_name': 'Tony Bradley',
  'first_name': 'Tony',
  'last_name': 'Bradley',
  'is_active': True},
 {'id': 1631103,
  'full_name': 'Malaki Branham',
  'first_name': 'Malaki',
  'last_name': 'Branham',
  'is_active': True},
 {'id': 1631128,
  'full_name': 'Christian Braun',
  'first_name': 'Christian',
  'last_name': 'Braun',
  'is_active': True},
 {'id': 1642886,
  'full_name': 'Koby Brea',
  'first_name': 'Koby',
  'last_name': 'Brea',
  'is_active': True},
 {'id': 1628969,
  'full_name': 'Mikal Bridges',
  'first_name': 'Mikal',
  'last_name': 'Bridges',
  'is_active': True},
 {'id': 1628970,
  'full_name': 'Miles Bridges',
  'first_name': 'Miles',
  'last_name': 'Bridges',
  'is_active': True},
 {'id': 1628415,
  'full_name': 'Dillon Brooks',
  'first_name': 'Dillon',
  'last_name': 'Brooks',
  'is_active': True},
 {'id': 1641780,
  'full_name': 'Johni Broome',
  'first_name': 'Johni',
  'last_name': 'Broome',
  'is_active': True},
 {'id': 1628971,
  'full_name': 'Bruce Brown',
  'first_name': 'Bruce',
  'last_name': 'Brown',
  'is_active': True},
 {'id': 1627759,
  'full_name': 'Jaylen Brown',
  'first_name': 'Jaylen',
  'last_name': 'Brown',
  'is_active': True},
 {'id': 1641738,
  'full_name': 'Kobe Brown',
  'first_name': 'Kobe',
  'last_name': 'Brown',
  'is_active': True},
 {'id': 1628973,
  'full_name': 'Jalen Brunson',
  'first_name': 'Jalen',
  'last_name': 'Brunson',
  'is_active': True},
 {'id': 1642868,
  'full_name': 'Carter Bryant',
  'first_name': 'Carter',
  'last_name': 'Bryant',
  'is_active': True},
 {'id': 1628418,
  'full_name': 'Thomas Bryant',
  'first_name': 'Thomas',
  'last_name': 'Bryant',
  'is_active': True},
 {'id': 202710,
  'full_name': 'Jimmy Butler III',
  'first_name': 'Jimmy',
  'last_name': 'Butler III',
  'is_active': True},
 {'id': 1641824,
  'full_name': 'Matas Buzelis',
  'first_name': 'Matas',
  'last_name': 'Buzelis',
  'is_active': True},
 {'id': 1631288,
  'full_name': 'Jamal Cain',
  'first_name': 'Jamal',
  'last_name': 'Cain',
  'is_active': True},
 {'id': 203484,
  'full_name': 'Kentavious Caldwell-Pope',
  'first_name': 'Kentavious',
  'last_name': 'Caldwell-Pope',
  'is_active': True},
 {'id': 1641739,
  'full_name': 'Toumani Camara',
  'first_name': 'Toumani',
  'last_name': 'Camara',
  'is_active': True},
 {'id': 203991,
  'full_name': 'Clint Capela',
  'first_name': 'Clint',
  'last_name': 'Capela',
  'is_active': True},
 {'id': 1642928,
  'full_name': 'Dylan Cardwell',
  'first_name': 'Dylan',
  'last_name': 'Cardwell',
  'is_active': True},
 {'id': 1642382,
  'full_name': 'Branden Carlson',
  'first_name': 'Branden',
  'last_name': 'Carlson',
  'is_active': True},
 {'id': 1642267,
  'full_name': 'Bub Carrington',
  'first_name': 'Bub',
  'last_name': 'Carrington',
  'is_active': True},
 {'id': 1642269,
  'full_name': 'Devin Carter',
  'first_name': 'Devin',
  'last_name': 'Carter',
  'is_active': True},
 {'id': 1628975,
  'full_name': 'Jevon Carter',
  'first_name': 'Jevon',
  'last_name': 'Carter',
  'is_active': True},
 {'id': 1628976,
  'full_name': 'Wendell Carter Jr.',
  'first_name': 'Wendell',
  'last_name': 'Carter Jr.',
  'is_active': True},
 {'id': 1627936,
  'full_name': 'Alex Caruso',
  'first_name': 'Alex',
  'last_name': 'Caruso',
  'is_active': True},
 {'id': 1642264,
  'full_name': 'Stephon Castle',
  'first_name': 'Stephon',
  'last_name': 'Castle',
  'is_active': True},
 {'id': 1630658,
  'full_name': 'Colin Castleton',
  'first_name': 'Colin',
  'last_name': 'Castleton',
  'is_active': True},
 {'id': 1630577,
  'full_name': 'Julian Champagnie',
  'first_name': 'Julian',
  'last_name': 'Champagnie',
  'is_active': True},
 {'id': 1630551,
  'full_name': 'Justin Champagnie',
  'first_name': 'Justin',
  'last_name': 'Champagnie',
  'is_active': True},
 {'id': 1642353,
  'full_name': 'Cam Christie',
  'first_name': 'Cam',
  'last_name': 'Christie',
  'is_active': True},
 {'id': 1631108,
  'full_name': 'Max Christie',
  'first_name': 'Max',
  'last_name': 'Christie',
  'is_active': True},
 {'id': 1630619,
  'full_name': 'Moussa Cisse',
  'first_name': 'Moussa',
  'last_name': 'Cisse',
  'is_active': True},
 {'id': 1631321,
  'full_name': 'Sidy Cissoko',
  'first_name': 'Sidy',
  'last_name': 'Cissoko',
  'is_active': True},
 {'id': 1641740,
  'full_name': 'Jaylen Clark',
  'first_name': 'Jaylen',
  'last_name': 'Clark',
  'is_active': True},
 {'id': 1629634,
  'full_name': 'Brandon Clarke',
  'first_name': 'Brandon',
  'last_name': 'Clarke',
  'is_active': True},
 {'id': 203903,
  'full_name': 'Jordan Clarkson',
  'first_name': 'Jordan',
  'last_name': 'Clarkson',
  'is_active': True},
 {'id': 1629651,
  'full_name': 'Nic Claxton',
  'first_name': 'Nic',
  'last_name': 'Claxton',
  'is_active': True},
 {'id': 1642383,
  'full_name': 'Walter Clayton Jr.',
  'first_name': 'Walter',
  'last_name': 'Clayton Jr.',
  'is_active': True},
 {'id': 1642363,
  'full_name': 'Nique Clifford',
  'first_name': 'Nique',
  'last_name': 'Clifford',
  'is_active': True},
 {'id': 1642270,
  'full_name': 'Donovan Clingan',
  'first_name': 'Donovan',
  'last_name': 'Clingan',
  'is_active': True},
 {'id': 1641730,
  'full_name': 'Noah Clowney',
  'first_name': 'Noah',
  'last_name': 'Clowney',
  'is_active': True},
 {'id': 1629599,
  'full_name': 'Amir Coffey',
  'first_name': 'Amir',
  'last_name': 'Coffey',
  'is_active': True},
 {'id': 1642268,
  'full_name': 'Isaiah Collier',
  'first_name': 'Isaiah',
  'last_name': 'Collier',
  'is_active': True},
 {'id': 1628381,
  'full_name': 'John Collins',
  'first_name': 'John',
  'last_name': 'Collins',
  'is_active': True},
 {'id': 1628380,
  'full_name': 'Zach Collins',
  'first_name': 'Zach',
  'last_name': 'Collins',
  'is_active': True},
 {'id': 201144,
  'full_name': 'Mike Conley',
  'first_name': 'Mike',
  'last_name': 'Conley',
  'is_active': True},
 {'id': 1626192,
  'full_name': 'Pat Connaughton',
  'first_name': 'Pat',
  'last_name': 'Connaughton',
  'is_active': True},
 {'id': 1631451,
  'full_name': 'Javonte Cooke',
  'first_name': 'Javonte',
  'last_name': 'Cooke',
  'is_active': True},
 {'id': 1630536,
  'full_name': 'Sharife Cooper',
  'first_name': 'Sharife',
  'last_name': 'Cooper',
  'is_active': True},
 {'id': 1641731,
  'full_name': 'Bilal Coulibaly',
  'first_name': 'Bilal',
  'last_name': 'Coulibaly',
  'is_active': True},
 {'id': 1642907,
  'full_name': 'Cedric Coward',
  'first_name': 'Cedric',
  'last_name': 'Coward',
  'is_active': True},
 {'id': 1642384,
  'full_name': 'Isaiah Crawford',
  'first_name': 'Isaiah',
  'last_name': 'Crawford',
  'is_active': True},
 {'id': 1630595,
  'full_name': 'Cade Cunningham',
  'first_name': 'Cade',
  'last_name': 'Cunningham',
  'is_active': True},
 {'id': 201939,
  'full_name': 'Stephen Curry',
  'first_name': 'Stephen',
  'last_name': 'Curry',
  'is_active': True},
 {'id': 1642359,
  'full_name': 'Pacôme Dadiet',
  'first_name': 'Pacôme',
  'last_name': 'Dadiet',
  'is_active': True},
 {'id': 1630700,
  'full_name': 'Dyson Daniels',
  'first_name': 'Dyson',
  'last_name': 'Daniels',
  'is_active': True},
 {'id': 1642368,
  'full_name': "N'Faly Dante",
  'first_name': "N'Faly",
  'last_name': 'Dante',
  'is_active': True},
 {'id': 203076,
  'full_name': 'Anthony Davis',
  'first_name': 'Anthony',
  'last_name': 'Davis',
  'is_active': True},
 {'id': 1631120,
  'full_name': 'JD Davison',
  'first_name': 'JD',
  'last_name': 'Davison',
  'is_active': True},
 {'id': 201942,
  'full_name': 'DeMar DeRozan',
  'first_name': 'DeMar',
  'last_name': 'DeRozan',
  'is_active': True},
 {'id': 1642484,
  'full_name': 'RayJ Dennis',
  'first_name': 'RayJ',
  'last_name': 'Dennis',
  'is_active': True},
 {'id': 1628978,
  'full_name': 'Donte DiVincenzo',
  'first_name': 'Donte',
  'last_name': 'DiVincenzo',
  'is_active': True},
 {'id': 1631217,
  'full_name': 'Moussa Diabaté',
  'first_name': 'Moussa',
  'last_name': 'Diabaté',
  'is_active': True},
 {'id': 1642885,
  'full_name': 'Mohamed Diawara',
  'first_name': 'Mohamed',
  'last_name': 'Diawara',
  'is_active': True},
 {'id': 1641711,
  'full_name': 'Gradey Dick',
  'first_name': 'Gradey',
  'last_name': 'Dick',
  'is_active': True},
 {'id': 1630621,
  'full_name': 'Hunter Dickinson',
  'first_name': 'Hunter',
  'last_name': 'Dickinson',
  'is_active': True},
 {'id': 1631172,
  'full_name': 'Ousmane Dieng',
  'first_name': 'Ousmane',
  'last_name': 'Dieng',
  'is_active': True},
 {'id': 1642265,
  'full_name': 'Rob Dillingham',
  'first_name': 'Rob',
  'last_name': 'Dillingham',
  'is_active': True},
 {'id': 1629029,
  'full_name': 'Luka Dončić',
  'first_name': 'Luka',
  'last_name': 'Dončić',
  'is_active': True},
 {'id': 1629652,
  'full_name': 'Luguentz Dort',
  'first_name': 'Luguentz',
  'last_name': 'Dort',
  'is_active': True},
 {'id': 1630245,
  'full_name': 'Ayo Dosunmu',
  'first_name': 'Ayo',
  'last_name': 'Dosunmu',
  'is_active': True},
 {'id': 203083,
  'full_name': 'Andre Drummond',
  'first_name': 'Andre',
  'last_name': 'Drummond',
  'is_active': True},
 {'id': 1627739,
  'full_name': 'Kris Dunn',
  'first_name': 'Kris',
  'last_name': 'Dunn',
  'is_active': True},
 {'id': 1642346,
  'full_name': 'Ryan Dunn',
  'first_name': 'Ryan',
  'last_name': 'Dunn',
  'is_active': True},
 {'id': 201142,
  'full_name': 'Kevin Durant',
  'first_name': 'Kevin',
  'last_name': 'Durant',
  'is_active': True},
 {'id': 1631105,
  'full_name': 'Jalen Duren',
  'first_name': 'Jalen',
  'last_name': 'Duren',
  'is_active': True},
 {'id': 1642856,
  'full_name': 'Egor Dëmin',
  'first_name': 'Egor',
  'last_name': 'Dëmin',
  'is_active': True},
 {'id': 1631106,
  'full_name': 'Tari Eason',
  'first_name': 'Tari',
  'last_name': 'Eason',
  'is_active': True},
 {'id': 1641744,
  'full_name': 'Zach Edey',
  'first_name': 'Zach',
  'last_name': 'Edey',
  'is_active': True},
 {'id': 1642845,
  'full_name': 'VJ Edgecombe',
  'first_name': 'VJ',
  'last_name': 'Edgecombe',
  'is_active': True},
 {'id': 1630162,
  'full_name': 'Anthony Edwards',
  'first_name': 'Anthony',
  'last_name': 'Edwards',
  'is_active': True},
 {'id': 1642348,
  'full_name': 'Justin Edwards',
  'first_name': 'Justin',
  'last_name': 'Edwards',
  'is_active': True},
 {'id': 1631165,
  'full_name': 'Keon Ellis',
  'first_name': 'Keon',
  'last_name': 'Ellis',
  'is_active': True},
 {'id': 203954,
  'full_name': 'Joel Embiid',
  'first_name': 'Joel',
  'last_name': 'Embiid',
  'is_active': True},
 {'id': 1642855,
  'full_name': 'Noa Essengue',
  'first_name': 'Noa',
  'last_name': 'Essengue',
  'is_active': True},
 {'id': 1630623,
  'full_name': 'Tyson Etienne',
  'first_name': 'Tyson',
  'last_name': 'Etienne',
  'is_active': True},
 {'id': 1629234,
  'full_name': 'Drew Eubanks',
  'first_name': 'Drew',
  'last_name': 'Eubanks',
  'is_active': True},
 {'id': 1641787,
  'full_name': 'Tosan Evbuomwan',
  'first_name': 'Tosan',
  'last_name': 'Evbuomwan',
  'is_active': True},
 {'id': 203957,
  'full_name': 'Danté Exum',
  'first_name': 'Danté',
  'last_name': 'Exum',
  'is_active': True},
 {'id': 1642847,
  'full_name': 'Jeremiah Fears',
  'first_name': 'Jeremiah',
  'last_name': 'Fears',
  'is_active': True},
 {'id': 1642271,
  'full_name': 'Kyle Filipowski',
  'first_name': 'Kyle',
  'last_name': 'Filipowski',
  'is_active': True},
 {'id': 1627827,
  'full_name': 'Dorian Finney-Smith',
  'first_name': 'Dorian',
  'last_name': 'Finney-Smith',
  'is_active': True},
 {'id': 1642843,
  'full_name': 'Cooper Flagg',
  'first_name': 'Cooper',
  'last_name': 'Flagg',
  'is_active': True},
 {'id': 1642853,
  'full_name': 'Rasheer Fleming',
  'first_name': 'Rasheer',
  'last_name': 'Fleming',
  'is_active': True},
 {'id': 1642280,
  'full_name': 'Trentyn Flowers',
  'first_name': 'Trentyn',
  'last_name': 'Flowers',
  'is_active': True},
 {'id': 1631323,
  'full_name': 'Simone Fontecchio',
  'first_name': 'Simone',
  'last_name': 'Fontecchio',
  'is_active': True},
 {'id': 1628368,
  'full_name': "De'Aaron Fox",
  'first_name': "De'Aaron",
  'last_name': 'Fox',
  'is_active': True},
 {'id': 1642402,
  'full_name': 'Enrique Freeman',
  'first_name': 'Enrique',
  'last_name': 'Freeman',
  'is_active': True},
 {'id': 1642277,
  'full_name': 'Johnny Furphy',
  'first_name': 'Johnny',
  'last_name': 'Furphy',
  'is_active': True},
 {'id': 1629655,
  'full_name': 'Daniel Gafford',
  'first_name': 'Daniel',
  'last_name': 'Gafford',
  'is_active': True},
 {'id': 1642066,
  'full_name': 'Myron Gardner',
  'first_name': 'Myron',
  'last_name': 'Gardner',
  'is_active': True},
 {'id': 1629636,
  'full_name': 'Darius Garland',
  'first_name': 'Darius',
  'last_name': 'Garland',
  'is_active': True},
 {'id': 1630568,
  'full_name': 'Luka Garza',
  'first_name': 'Luka',
  'last_name': 'Garza',
  'is_active': True},
 {'id': 1641718,
  'full_name': 'Keyonte George',
  'first_name': 'Keyonte',
  'last_name': 'George',
  'is_active': True},
 {'id': 1642273,
  'full_name': 'Kyshawn George',
  'first_name': 'Kyshawn',
  'last_name': 'George',
  'is_active': True},
 {'id': 202331,
  'full_name': 'Paul George',
  'first_name': 'Paul',
  'last_name': 'George',
  'is_active': True},
 {'id': 1630581,
  'full_name': 'Josh Giddey',
  'first_name': 'Josh',
  'last_name': 'Giddey',
  'is_active': True},
 {'id': 1628983,
  'full_name': 'Shai Gilgeous-Alexander',
  'first_name': 'Shai',
  'last_name': 'Gilgeous-Alexander',
  'is_active': True},
 {'id': 1630264,
  'full_name': 'Anthony Gill',
  'first_name': 'Anthony',
  'last_name': 'Gill',
  'is_active': True},
 {'id': 1631221,
  'full_name': 'Collin Gillespie',
  'first_name': 'Collin',
  'last_name': 'Gillespie',
  'is_active': True},
 {'id': 203497,
  'full_name': 'Rudy Gobert',
  'first_name': 'Rudy',
  'last_name': 'Gobert',
  'is_active': True},
 {'id': 1642884,
  'full_name': 'Vladislav Goldin',
  'first_name': 'Vladislav',
  'last_name': 'Goldin',
  'is_active': True},
 {'id': 1642864,
  'full_name': 'Hugo González',
  'first_name': 'Hugo',
  'last_name': 'González',
  'is_active': True},
 {'id': 1630692,
  'full_name': 'Jordan Goodwin',
  'first_name': 'Jordan',
  'last_name': 'Goodwin',
  'is_active': True},
 {'id': 203932,
  'full_name': 'Aaron Gordon',
  'first_name': 'Aaron',
  'last_name': 'Gordon',
  'is_active': True},
 {'id': 201569,
  'full_name': 'Eric Gordon',
  'first_name': 'Eric',
  'last_name': 'Gordon',
  'is_active': True},
 {'id': 203924,
  'full_name': 'Jerami Grant',
  'first_name': 'Jerami',
  'last_name': 'Grant',
  'is_active': True},
 {'id': 1631260,
  'full_name': 'AJ Green',
  'first_name': 'AJ',
  'last_name': 'Green',
  'is_active': True},
 {'id': 203110,
  'full_name': 'Draymond Green',

In [52]:
for player in cur_players:
    if player['id'] == 1631200:
        print(player)

{'id': 1631200, 'full_name': 'Kris Murray', 'first_name': 'Kris', 'last_name': 'Murray', 'is_active': True}

UNABLE TO USE nba_api due to rate limit introduced in 2023!!

BUST!!